### PR TITLE
Move to qtpy

### PR DESCRIPTION
**Pull request by rosswhitfield**
For [REF96](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/96)

You should be able to start it with 

```
QT_API=pyqt scripts/start_refred.py
```

### CODE REVIEW

**Review by wdzhou — COMMENTED** [review]
It is better to point out, maybe in README_developer.rst, that the default python2 on SNS analysis cluster is from conda, which does not support qtpy well.

I need to run 
```
QT_API=pyqt /user/bin/python scripts/start_refred.py
```
instead.

**Comment by rosswhitfield** [comment]
> the default python2 on SNS analysis cluster is from conda

No it's not, you must have conda activated by default.

**Comment by wdzhou** [comment]
Error is found when running https://github.com/neutrons/RefRed/blob/next/docs/load-template.rst.

QtCore does not have QStringList in pyqt.

**Comment by rosswhitfield** [comment]
> Error is found when running https://github.com/neutrons/RefRed/blob/next/docs/load-template.rst.
> 
> QtCore does not have QStringList in pyqt.

Should be fixed now.

**Comment by wdzhou** [comment]
**2nd Error Found**

When running the use case 'Reduction', after I pushed the button 'Reduce'

```
....

Traceback (most recent call last):
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/main.py", line 388, in run_reduction_button
    o_live_reduction.run()
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/reduction/live_reduction_handler.py", line 86, in run
    o_reduced_plot.populate_table()
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/reduction/live_reduced_data_handler.py", line 24, in populate_table
    o_fill_table.fillRow(row_index=self.row_index)
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/gui_handling/fill_stitching_table.py", line 28, in fillRow
    self.fillTableRunNumber()
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/gui_handling/fill_stitching_table.py", line 41, in fillTableRunNumber
    _run_item = QtWidgets.QTableWidgetItem(_run_number)
NameError: global name 'QtWidgets' is not defined


```

**Comment by wdzhou** [comment]
**3rd Error Found**

When running the use case for `sf calculator`, this error showed as I entered the run numbers

```

...

Rebin-[Information]   Name: FullBinsOnly, Value: 0, Default?: Yes, Direction: Input
Rebin-[Information]   Name: IgnoreBinErrors, Value: 0, Default?: Yes, Direction: Input
Rebin-[Notice] Rebin successful, Duration 0.05 seconds
Traceback (most recent call last):
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/sf_calculator.py", line 183, in runSequenceLineEditEvent
    read_options=self.read_options,
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/load_and_sort_nxsdata_for_sf_calculator.py", line 34, in __init__
    self.loadNXSData()
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/load_and_sort_nxsdata_for_sf_calculator.py", line 56, in loadNXSData
    self.sf_gui.update_table(self, False)
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/sf_calculator.py", line 166, in update_table
    self.fillGuiTable()
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/sf_calculator.py", line 515, in fillGuiTable
    is_using_si_slits=self.is_using_si_slits)
  File "/SNS/users/wzz/Projects/Reflectometry/RefRed/RefRed/sf_calculator/fill_sf_gui_table.py", line 48, in __init__
    _item = QtWidgets.QTableWidgetItem("ACTIVE")
NameError: global name 'QtWidgets' is not defined


```

**Comment by wdzhou** [comment]
@rosswhitfield I found another 2 bugs reported above.  After I fixed them in https://github.com/neutrons/RefRed/pull/23/commits/65271beaa1883403b4004fa6e69bd32021e099d4, all 3 @mdoucet 's user cases can be executed.  

I am not sure whether I am eligible to merge this PR anymore.

**Comment by rosswhitfield** [comment]
> @rosswhitfield I found another 2 bugs reported above. After I fixed them in [65271be](https://github.com/neutrons/RefRed/commit/65271beaa1883403b4004fa6e69bd32021e099d4), all 3 @mdoucet 's user cases can be executed.
> 
> I am not sure whether I am eligible to merge this PR anymore.

Thanks, I found a few more places that I forgot to import QtWidgets :grin:

**Review by wdzhou — APPROVED** [review]
It passes all three "official" use cases. 

Time to merge.

**Pull request merged**
